language: cpp

dist: xenial

matrix:
  include:
    - name: "MacOS"
      os: osx
      compiler: clang
      env: OS=osx COMPILER=clang
      osx_image: xcode11
      addons:
        homebrew:
          update: true
          packages:
            - flex
            - bison


before_install:
  # gcc
  - if [ "$OS" != "osx" ] && [ "$COMPILER" = "gcc" ]; then export CC="gcc-${GCC_VERSION}" CXX="g++-${GCC_VERSION}"; fi
  # clang, libc++, libc++abi
  - if [ "$OS" != "osx" ] && [ "$COMPILER" = "clang" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}"; fi
  # brew, doxygen, graphviz
  - if [ "$OS" == "osx" ]; then brew update && echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.bash_profile; && source ~/.bash_profile fi
  # cmake
  - cmake --version
  - bison --version
  - flex --version

script: 
  - bash build.sh